### ISSUE TITLE
Multi Language Support

### ISSUE THREAD

**Issue by tu2-atmanand** [tu2-atmanand/Task-Board#56]
> **Very Important feature to get more popularity**

This is very simple thing to integrate, take the whole code from either CardBoard or see other bigger projects like Kanban and all. You simply have to create a folder, have those functions c("Text Here"), etc. Then Wherever you are showing strings to user, just replace that content with the function, inside that you will put your English Content.
Dont have to worry about rest of the data.

**Comment by GardarikanetS** [comment]
Hello. Since you are using auto-translation, it would be reasonable to add a separate drag-and-drop menu to the General, where the user can choose the language himself. At the moment, the problem is that when reading auto-translation in my native language, it is easier for me to switch Obsidian itself to English than to figure out what the machine has translated.

Later, if I like the plugin, I will contribute to it by really translating it into Russian

**Comment by tu2-atmanand** [comment]
Hi @GardarikanetS 

Thank you for creating this issue and showing your support for contribution to this plugin.

Actually, having a separate drop down menu for changing the language for Task Board specifically is against the guidelines/best practices of Obsidian. I actually had this feature, before the release, but the [reviewers told](https://github.com/obsidianmd/obsidian-releases/pull/4567#issuecomment-2501674257) me to remove it and go with the approach of translating the plugin language according to the global Obsidian language itself, to maintain consistency throughout the software.

So, having a separate setting specifically for this plugin doesnt seem to be a good idea and mostly wont be implemented.

But, I would love it, if you can improve the content which I have translated using Google's free API to something more sensible, so every other user who is using this plugin can have a better experience. Your contribution will mean a lot to all the Task Board users.

Thank you!
